name: dppo_310
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - glew=2.1.0
  - icu=73.1
  - kernel-headers_linux-64=3.10.0
  - ld_impl_linux-64=2.44
  - libdrm=2.4.124
  - libdrm-cos7-x86_64=2.4.97
  - libegl=1.7.0
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglu=9.0.0
  - libglvnd=1.7.0
  - libglvnd-cos7-x86_64=1.0.1
  - libglvnd-glx-cos7-x86_64=1.0.1
  - libgomp=15.2.0
  - libllvm20=20.1.8
  - libnsl=2.0.0
  - libopengl=1.7.0
  - libopengl-devel=1.7.0
  - libpciaccess=0.18
  - libstdcxx=15.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - mesa-khr-devel-cos7-x86_64=18.3.4
  - mesa-libgl-cos7-x86_64=18.3.4
  - mesa-libgl-devel-cos7-x86_64=18.3.4
  - mesa-libglapi-cos7-x86_64=18.3.4
  - mesalib=25.0.5
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - pyopengl=3.1.10
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - spirv-tools=2024.3
  - sqlite=3.50.2
  - sysroot_linux-64=2.17
  - tk=8.6.15
  - tzdata=2025b
  - wayland=1.24.0
  - wheel=0.45.1
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcursor=1.2.3
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
    - abnf==2.2.0
    - absl-py==2.3.1
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.2
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.11.0
    - async-timeout==5.0.1
    - attrs==25.4.0
    - av==12.3.0
    - backoff==2.2.1
    - beautifulsoup4==4.14.2
    - certifi==2025.10.5
    - cffi==2.0.0
    - chardet==5.2.0
    - charset-normalizer==3.4.4
    - cint==1.0.0
    - click==8.3.0
    - cmake==4.1.2
    - cmeel==0.57.3
    - cmeel-assimp==5.4.3.1
    - cmeel-boost==1.83.0
    - cmeel-console-bridge==1.0.2.3
    - cmeel-octomap==1.10.0
    - cmeel-qhull==8.0.2.1
    - cmeel-tinyxml==2.6.2.3
    - cmeel-urdfdom==3.1.1.1
    - cmeel-zlib==1.3.1
    - colorama==0.4.6
    - contourpy==1.3.2
    - cryptography==46.0.3
    - cycler==0.12.1
    - cython==0.29.37
    - d3il-sim==0.2
    - d4rl==1.1
    - daqp==0.7.2
    - diskcache==5.6.3
    - dm-control==1.0.34
    - dm-env==1.6
    - dm-tree==0.1.9
    - docker-pycreds==0.4.0
    - dppo==0.8.0
    - eigenpy==3.5.1
    - einops==0.8.0
    - etils==1.13.0
    - eval-type-backport==0.2.2
    - evdev==1.9.2
    - farama-notifications==0.0.4
    - fasteners==0.20
    - fickling==0.1.4
    - filelock==3.20.0
    - fonttools==4.60.1
    - frozenlist==1.8.0
    - fsspec==2025.10.0
    - gdown==5.2.0
    - gin-config==0.5.0
    - gitdb==4.0.12
    - gitpython==3.1.45
    - glfw==2.10.0
    - gql==4.0.0
    - graphql-core==3.2.6
    - gym==0.22.0
    - gym-avoiding==0.0.1
    - gym-notices==0.1.0
    - gymnasium==1.2.1
    - h5py==3.15.1
    - hpp-fcl==2.4.4
    - hydra-core==1.3.2
    - idna==3.11
    - imageio==2.35.1
    - importlib-resources==6.5.2
    - iniconfig==2.3.0
    - intervaltree==3.1.0
    - jinja2==3.1.6
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - kaitaistruct==0.11
    - kiwisolver==1.4.9
    - labmaze==1.0.6
    - llvmlite==0.45.1
    - markupsafe==3.0.3
    - matplotlib==3.7.5
    - mink==0.0.13
    - mujoco==3.3.7
    - mujoco-py==2.1.2.14
    - multidict==6.7.0
    - networkx==3.4.2
    - numba==0.62.1
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.9.86
    - nvidia-nvtx-cu12==12.1.105
    - omegaconf==2.3.0
    - opencv-python==4.12.0.88
    - opencv-python-headless==4.12.0.88
    - packaging==25.0
    - patchelf==0.17.2.4
    - pdfminer-six==20250506
    - pillow==12.0.0
    - pin==2.7.0
    - platformdirs==4.5.0
    - pluggy==1.6.0
    - polyfile-weave==0.5.7
    - pretty-errors==1.2.25
    - propcache==0.4.1
    - protobuf==5.29.5
    - psutil==7.1.2
    - pybullet==3.2.7
    - pycparser==2.23
    - pydantic==2.11.10
    - pydantic-core==2.33.2
    - pygments==2.19.2
    - pynput==1.8.1
    - pyparsing==3.2.5
    - pysocks==1.7.1
    - pytest==8.4.2
    - python-graphviz==0.21
    - python-xlib==0.33
    - pyyaml==6.0.3
    - qpsolvers==4.8.1
    - referencing==0.37.0
    - requests==2.32.5
    - requests-toolbelt==1.0.0
    - robomimic==0.3.0
    - robosuite==1.4.1
    - rpds-py==0.28.0
    - scipy==1.15.3
    - sentry-sdk==2.43.0
    - setproctitle==1.3.7
    - six==1.17.0
    - smmap==5.0.2
    - soupsieve==2.8
    - stdlib-list==0.11.1
    - tenacity==9.1.2
    - tomli==2.3.0
    - torch==2.4.0
    - tqdm==4.66.5
    - triton==3.0.0
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - urllib3==2.5.0
    - wandb==0.17.7
    - weave==0.52.11
    - yarl==1.22.0
    - zipp==3.23.0
prefix: /home/kzy816/.conda/envs/dppo_310
